const Products = [
  {
    id:280,
    name: "Iphone 14 Pro",
    price: 999,
    img: "iphone14.png",
    colors: ["iphone14.png", "iphone14w.png"],
    width: 100,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-brown",
    wishlist: false,
    quantity:1,
    section:'ios',
    top:true,
  },
  {
    id:281,
    name: "Iphone 14 Pro",
    price: 999,
    img: "iphone14.png",
    colors: ["iphone14.png", "iphone14w.png"],
    width: 100,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-brown",
    wishlist: false,
    quantity:1,
    section:'ios',
  },
  {
    id:282,
    name: "Iphone 14 Pro",
    price: 999,
    img: "iphone14.png",
    colors: ["iphone14.png","iphone14w.png"],
    width: 100,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-brown",
    wishlist: false,
    quantity:1,
    section:'ios',
  },
  {
    id:283,
    name: "Iphone 14 Pro",
    price: 999,
    img: "iphone14.png",
    colors: ["iphone14.png", "iphone14w.png"],
    width: 100,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-brown",
    wishlist: false,
    quantity:1,
    section:'ios',
  },
  {
    id:314,
    name: "Samsung note 20 ultra",
    price: 999,
    img: "sn20w.png",
    colors: ["sn20w.png", "sn20.png"],
    width: 110,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-blue",
    wishlist: false,
    quantity:1,
    section:'android',
  },
  {
    id:315,
    name: "Samsung note 20 ultra",
    price: 999,
    img: "sn20w.png",
    colors: ["sn20w.png", "sn20.png"],
    width: 110,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-blue",
    wishlist: false,
    quantity:1,
    section:'android',
  },
  {
    id:316,
    name: "Samsung note 20 ultra",
    price: 999,
    img: "sn20w.png",
    colors: ["sn20w.png", "sn20.png"],
    width: 110,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-blue",
    wishlist: false,
    quantity:1,
    section:'android',
  },
  {
    id:317,
    name: "Samsung note 20 ultra",
    price: 999,
    img: "sn20w.png",
    colors: ["sn20w.png", "sn20.png"],
    width: 110,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-blue",
    wishlist: false,
    quantity:1,
    section:'android',
  },
  {
    id:2944,
    name: "Galaxy Watch",
    price: 799,
    img: "watch.png",
    colors: ["watch.png", "watch2.png"],
    sizes: ["40mm", "44mm", "45mm"],
    width: 110,
    bacColor: "l-blue",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:'watch',
    top:true,
  },
  {
    id:2933,
    name: "Galaxy Watch",
    price: 799,
    img: "watch.png",
    colors: ["watch.png", "watch2.png"],
    sizes: ["40mm", "44mm", "45mm"],
    width: 110,
    bacColor: "l-blue",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:'watch',
  },
  {
    id:29222,
    name: "Galaxy Watch",
    price: 799,
    img: "watch.png",
    colors: ["watch.png", "watch2.png"],
    sizes: ["40mm", "44mm", "45mm"],
    width: 110,
    bacColor: "l-blue",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:'watch',
  },
  {
    id:2911,
    name: "Galaxy Watch",
    price: 799,
    img: "watch.png",
    colors: ["watch.png", "watch2.png"],
    sizes: ["40mm", "44mm", "45mm"],
    width: 110,
    bacColor: "l-blue",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:'watch',
  },
  {
    id: 1,
    name: "T-Shirt Name",
    price: 199,
    img: "shirt.png",
    colors: ["shirt.png"],
    sizes:["X","XX","XL"],
    width: 100,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-blue",
    wishlist: false,
    quantity:1,
    section:'shirt',
  },
  {
    id: 2,
    name: "T-Shirt Name",
    price: 199,
    img: "shirt.png",
    colors: ["shirt.png"],
    sizes:["X","XX","XL"],
    width: 100,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-blue",
    wishlist: false,
    quantity:1,
    section:'shirt',
  },
  {
    id: 3,
    name: "T-Shirt Name",
    price: 199,
    img: "shirt.png",
    colors: ["shirt.png"],
    sizes:["X","XX","XL"],
    width: 100,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-blue",
    wishlist: false,
    quantity:1,
    section:'shirt',
  },
  {
    id: 4,
    name: "T-Shirt Name",
    price: 199,
    img: "shirt.png",
    colors: ["shirt.png"],
    sizes:["X","XX","XL"],
    width: 100,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-blue",
    wishlist: false,
    quantity:1,
    section:'shirt',
  },
  {
    id: 391,
    name: "Trouser Name",
    price: 249,
    img: "trousers.png",
    colors: ["trousers.png"],
    sizes:["30","32","35"],
    width: 60,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-brown",
    wishlist: false,
    quantity:1,
    section:'trouser',
  },
  {
    id: 392,
    name: "Trouser Name",
    price: 249,
    img: "trousers.png",
    colors: ["trousers.png"],
    sizes:["30","32","35"],
    width: 60,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-brown",
    wishlist: false,
    quantity:1,
    section:'trouser',
  },
  {
    id: 393,
    name: "Trouser Name",
    price: 249,
    img: "trousers.png",
    colors: ["trousers.png"],
    sizes:["30","32","35"],
    width: 60,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-brown",
    wishlist: false,
    quantity:1,
    section:'trouser',
  },
  {
    id: 394,
    name: "Trouser Name",
    price: 249,
    img: "trousers.png",
    colors: ["trousers.png"],
    sizes:["30","32","35"],
    width: 60,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-brown",
    wishlist: false,
    quantity:1,
    section:'trouser',
  },
  {
    id: 41,
    name: "Shoes Name",
    price: 499,
    img: "shoes.png",
    colors: ["shoes.png"],
    sizes:["37","39","40","42","44","45","46"],
    width: 160,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-blue",
    wishlist: false,
    quantity:1,
    section:'shoes',
  },
  {
    id: 42,
    name: "Shoes Name",
    price: 499,
    img: "shoes.png",
    colors: ["shoes.png"],
    sizes:["37","39","40","42","44","45","46"],
    width: 160,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-blue",
    wishlist: false,
    quantity:1,
    section:'shoes',
  },
  {
    id: 43,
    name: "Shoes Name",
    price: 499,
    img: "shoes.png",
    colors: ["shoes.png"],
    sizes:["37","39","40","42","44","45","46"],
    width: 160,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-blue",
    wishlist: false,
    quantity:1,
    section:'shoes',
  },
  {
    id: 44,
    name: "Shoes Name",
    price: 499,
    img: "shoes.png",
    colors: ["shoes.png"],
    sizes:["37","39","40","42","44","45","46"],
    width: 160,
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    bacColor: "l-blue",
    wishlist: false,
    quantity:1,
    section:'shoes',
  },
  {
    id: 84030,
    name: "x1506 Case",
    price: 599,
    img: "case.png",
    colors: ["case.png"],
    width: 120,
    bacColor: "l-brown",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:'case',
    top:true,
  },
  {
    id: 184030,
    name: "x1506 Case",
    price: 599,
    img: "case.png",
    colors: ["case.png"],
    width: 120,
    bacColor: "l-brown",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:'case',
  },
  {
    id: 284030,
    name: "x1506 Case",
    price: 599,
    img: "case.png",
    colors: ["case.png"],
    width: 120,
    bacColor: "l-brown",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:'case',
  },
  {
    id: 5030,
    name: "x1506 Case",
    price: 599,
    img: "case.png",
    colors: ["case.png"],
    width: 120,
    bacColor: "l-brown",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:'case',
  },
  {
    id: 7035,
    name: "Redragon M910-KS",
    price: 129,
    img: "mouse.png",
    colors: ["mouse.png"],
    width: 80,
    bacColor: "l-blue",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:'mouse',
  },
  {
    id: 8035,
    name: "Redragon M910-KS",
    price: 129,
    img: "mouse.png",
    colors: ["mouse.png"],
    width: 80,
    bacColor: "l-blue",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:'mouse',
  },
  {
    id: 9035,
    name: "Redragon M910-KS",
    price: 129,
    img: "mouse.png",
    colors: ["mouse.png"],
    width: 80,
    bacColor: "l-blue",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:'mouse',
  },
  {
    id: 4035,
    name: "Redragon M910-KS",
    price: 129,
    img: "mouse.png",
    colors: ["mouse.png"],
    width: 80,
    bacColor: "l-blue",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:'mouse',
  },
  {
    id: 54040,
    name: "Razer Huntsman Mini",
    price: 299,
    img: "keyboard.png",
    colors: ["keyboard.png"],
    width: 170,
    bacColor: "l-blue",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:'keyboard',
  },
  {
    id: 4131,
    name: "Canon Camera",
    price: 1999,
    img: "camera.png",
    colors: ["camera.png"],
    width: 130,
    bacColor: "l-blue",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:"camera",
    top:true,
  },
  {
    id: 4231,
    name: "Canon Camera",
    price: 1999,
    img: "camera.png",
    colors: ["camera.png"],
    width: 130,
    bacColor: "l-blue",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:"camera",
  },
  {
    id: 4331,
    name: "Canon Camera",
    price: 1999,
    img: "camera.png",
    colors: ["camera.png"],
    width: 130,
    bacColor: "l-blue",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:"camera",
  },
  {
    id: 4431,
    name: "Canon Camera",
    price: 1999,
    img: "camera.png",
    colors: ["camera.png"],
    width: 130,
    bacColor: "l-blue",
    disc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    added: false,
    wishlist: false,
    quantity:1,
    section:"camera",
  },
];
export default Products;